import { type NextPage } from "next";
import Head from "next/head";
import Search from "~/components/Search";
import AsyncSearch from "~/components/AsyncSearch";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen bg-gray-200 flex justify-center items-center">
        <div className="bg-white flex-col md:h-3/5 md:w-2/5 flex justify-center items-center ">
          <div className="flex-grow flex flex-col justify-center items-center ">
            <h1 className="mb-2">Async search</h1>
            <AsyncSearch />
            <h1 className="mt-2">
              With description and custom results display
            </h1>
          </div>
          <div className="flex-grow flex flex-col justify-center items-center">
            <h1 className="mb-2">Sync search</h1>
            <Search />
            <h1 className="mt-2">With default display and search on focus</h1>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
