import { type NextPage } from "next";
import Head from "next/head";
import { RiAdminFill } from "react-icons/ri";
import Job from "~/components/Job";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-row min-h-screen h-full w-full bg-zinc-300">
          <div className=" flex-1 flex flex-col h-full ">
            <Job
              companyUrl={"/images/Govtech.png"}
              companyName="GovTech"
              rating="4"
              title="Technical Product Manager"
              role="Cloud"
              time="less than a minute ago"
              focusArea="PM"
              skills={["play", "IAM"]}
            />
            <Job
              companyUrl={"/images/Govtech.png"}
              companyName="Coupang"
              rating="3.9"
              title="Staff, Back-end Engineer"
              role="COupang Play"
              time="37 minutes ago"
              focusArea="Backend"
              skills={["Rest API", "API", "play", "Modular", "Node.js"]}
            />
            <Job
              companyUrl={"/images/Govtech.png"}
              companyName="Embed"
              rating="3.5"
              title="Senior Software Engineer"
              role=".Net"
              time="about 1 hour ago"
              focusArea="Fullstack"
              skills={["Rest API", "Docker", "API", "TDD", "JavaScript"]}
            />
            <Job
              companyUrl={"/images/Govtech.png"}
              companyName="Circles.Life"
              rating="3"
              title="Principal Engineer"
              role="Cloud"
              time="less than a minute ago"
              focusArea="pm"
              skills={["play", "IAM"]}
            />
          </div>
          <div className="bg-white md:block flex-1 m-3 hidden">
            <h1>JOB TITLE</h1>
            <p>
              to narrow the scope of the task, you do not need to build the UI
              of this right panel
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
